services:
  app:
    image: bfu_mega_laba
    build:
      context: .
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    env_file: 
      - ./.env.dev
  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    healthcheck: 
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file: 
      - ./.env.dev
