# Generated by Django 5.2 on 2025-04-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=255)),
                ('rate', models.DecimalField(decimal_places=7, max_digits=15)),
                ('actual_date', models.DateField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_modified', models.BooleanField(default=False)),
            ],
        ),
    ]
