# Generated by Django 5.2 on 2025-04-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='is_deleted',
            field=models.DateField(blank=True, null=True),
        ),
    ]
