# Generated by Django 5.2 on 2025-04-08 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_alter_currency_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='is_deleted',
            new_name='deleted_date',
        ),
    ]
